# Generated by Django 5.1.3 on 2024-11-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_type', models.CharField(default='Raspberry PI', max_length=100)),
                ('installation_date', models.DateField(auto_now=True)),
                ('hub_status', models.CharField(default='working', max_length=100)),
                ('name', models.CharField(default='My House', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='hub_pics/default.jpg', upload_to='hub_pics/')),
            ],
        ),
    ]
