# Generated by Django 5.1.3 on 2024-12-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='picture',
            field=models.ImageField(default='photo/hub_pics/default.jpg', upload_to='hub_pics/'),
        ),
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(default='Arduino', max_length=100)),
                ('installation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField()),
                ('last_transmitted_telematry', models.JSONField()),
                ('plant_ref', models.CharField(default='Generic culture', max_length=100)),
                ('parent_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.hub')),
            ],
        ),
    ]
