# Generated by Django 5.1.3 on 2025-01-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_hub_picture_sensordevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordevice',
            name='last_transmitted_telematry',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='last_update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
