# Generated by Django 5.1.3 on 2025-01-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_alter_sensordevice_last_transmitted_telematry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telematry_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(auto_now=True)),
                ('is_last_transmitted', models.BooleanField(default=True)),
                ('previously_transmitted', models.IntegerField(null=True)),
                ('next_transmitted', models.IntegerField(null=True)),
                ('humidity', models.FloatField()),
                ('parent_hub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.hub')),
                ('parent_sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.sensordevice')),
            ],
        ),
    ]
