# Generated by Django 5.1.3 on 2025-01-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_sensordevice_last_transmitted_telematry_and_more'),
        ('telematry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Telematry_Data',
            new_name='TelematryData',
        ),
    ]
