# Generated by Django 5.1.2 on 2025-02-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raspberry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_owner', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('humidity', models.JSONField()),
                ('temperature', models.JSONField()),
                ('water', models.JSONField()),
                ('fk_raspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.raspberry')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_associated', models.BooleanField()),
                ('fk_garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.garden')),
            ],
        ),
    ]
