# Generated by Django 5.1.2 on 2025-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raspberry',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
