# Generated by Django 5.1.2 on 2025-04-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_garden_id_alter_raspberry_id_alter_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='humidity',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='garden',
            name='temperature',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='garden',
            name='water',
            field=models.JSONField(default=list),
        ),
    ]
