# Generated by Django 5.1.2 on 2025-04-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_garden_humidity_alter_garden_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='fk_garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.garden'),
        ),
    ]
