# Generated by Django 5.1.2 on 2025-04-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_sensor_fk_garden'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='plants',
            field=models.JSONField(default=list),
        ),
    ]
