# Generated by Django 5.1.2 on 2025-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sensor_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='name',
            field=models.CharField(default='Garden', max_length=50),
        ),
    ]
