# Generated by Django 5.1.2 on 2025-04-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_garden_humidity_remove_garden_plants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='plants',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='garden',
            name='moisture',
            field=models.JSONField(default=list),
        ),
    ]
