# Generated by Django 5.1.2 on 2025-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_garden_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='idSensor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
