# Generated by Django 5.2 on 2025-04-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='water',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
