# Generated by Django 5.1.2 on 2025-04-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_sensor_idsensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='fk_raspberry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.raspberry'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='idSensor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
