# Generated by Django 5.1.2 on 2025-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='status',
            field=models.CharField(default='not working', max_length=50),
        ),
    ]
