# Generated by Django 5.1.2 on 2025-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_garden_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_owner', models.CharField(max_length=50)),
                ('telegram_id', models.CharField(max_length=10)),
            ],
        ),
    ]
