# Generated by Django 5.2 on 2025-04-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_water_id_alter_water_timestamp'),
        ('accounts', '0019_alter_garden_status'),
    ]

    operations = [
    ]
