# Generated by Django 5.1.2 on 2025-04-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20250411_1850'),
        ('accounts', '0020_telegram'),
    ]

    operations = [
    ]
