# Generated by Django 5.1.2 on 2025-04-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_0020_merge_20250411_1850_0020_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='garden',
            name='location',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='garden',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='garden',
            name='surface_area',
            field=models.FloatField(default=0.0),
        ),
    ]
