# Generated by Django 5.2 on 2025-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='entered',
            field=models.BooleanField(default=False),
        ),
    ]
