# Generated by Django 5.1.2 on 2024-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Previsione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('meteo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Previsione',
            },
        ),
    ]
