# Generated by Django 5.1.2 on 2025-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previsione',
            old_name='data',
            new_name='ora',
        ),
        migrations.AddField(
            model_name='previsione',
            name='anno',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='previsione',
            name='giorno',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='previsione',
            name='mese',
            field=models.IntegerField(default=12),
        ),
    ]
