# Generated by Django 5.1.2 on 2025-03-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_data_previsione_ora_previsione_anno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsione',
            name='ora',
        ),
    ]
