# Generated by Django 5.1.2 on 2025-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_previsione_ora'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsione',
            name='dm',
            field=models.IntegerField(default=0),
        ),
    ]
