# Generated by Django 5.1.2 on 2025-04-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_previsione_dm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsione',
            name='meteo',
        ),
        migrations.AddField(
            model_name='previsione',
            name='codici',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='previsione',
            name='temp_max',
            field=models.FloatField(default=15.5),
        ),
        migrations.AddField(
            model_name='previsione',
            name='temp_min',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='previsione',
            name='anno',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='previsione',
            name='mese',
            field=models.IntegerField(default=4),
        ),
    ]
