# Generated by Django 5.1.2 on 2025-04-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_previsione_meteo_previsione_codici_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsione',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='previsione',
            name='giorno',
        ),
        migrations.RemoveField(
            model_name='previsione',
            name='mese',
        ),
        migrations.AddField(
            model_name='previsione',
            name='AMG',
            field=models.CharField(default='2023-04-04', max_length=50),
        ),
    ]
